### ISSUE TITLE
short_term forecasting

### ISSUE THREAD

**Issue by sangg-0** [thuml/AutoTimes#17]
您好，非常感谢您所做出的杰出的工作，相信它一定能推动学界相关领域的进步。
  我在复现您工作中的M4_short_term_forecasting时遇到了一些问题，我发现您的short_term_forecasting的代码中并没有用到您论文中所提到的两大创新点—文本时间戳嵌入、上下文预测。请问在short_term_forecasting的工作中，您是否没有采用这两个方法呢，亦或是我对于您的代码理解有误？
  真诚地期待您的回复，祝好。

**Comment by hvlgo** [comment]
The reason for not using timestamps is that the M3 and M4 datasets do not include timestamp information. Each sequence in these datasets only has a starting point in time, and most of these are default placeholder values rather than actual timestamps. Of course, if a way to construct timestamp sequences is devised, adding them would certainly be useful. As for the context forecasting code, it is located in exp_in_context_forecasting, and the experiments include the M3 and M4 datasets.

**Comment by sangg-0** [comment]
I get it, Thank you very much for your reply！

> The reason for not using timestamps is that the M3 and M4 datasets do not include timestamp information. Each sequence in these datasets only has a starting point in time, and most of these are default placeholder values rather than actual timestamps. Of course, if a way to construct timestamp sequences is devised, adding them would certainly be useful. As for the context forecasting code, it is located in exp_in_context_forecasting, and the experiments include the M3 and M4 datasets.
